#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    __DIR__.'/vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (\file_exists($file)) {
        require $file;
        break;
    }
}

use function Innmind\GitRelease\bootstrap;
use Innmind\CLI\{
    Main,
    Environment,
};
use Innmind\OperatingSystem\OperatingSystem;
use Innmind\Url\Path;
use Innmind\Immutable\{
    Str,
    Attempt,
};

new class extends Main {
    #[\Override]
    protected function main(Environment $env, OperatingSystem $os): Attempt
    {
        return $env
            ->variables()
            ->get('HOME')
            ->map(Path::of(...))
            ->map(static fn($home) => bootstrap($os, $home))
            ->match(
                static fn($run) => $run($env),
                static fn() => $env
                    ->exit(1)
                    ->output(Str::of("HOME env variable missing\n")),
            );
    }
};

